export const theme = {
  colors: {
    bg: "#ffffff",
    sidebarBg: "#f8f9fa",
    sidebarBorder: "#e0e0e0",
    headerBg: "#ffffff",
    headerBorder: "#e0e0e0",
    primary: "#1976d2",
    danger: "#d32f2f",
    text: "#212121",
    textSecondary: "#616161",
    textMuted: "#9e9e9e",
    border: "#ccc",
    borderLight: "#eee",
    tabActive: "#1976d2",
    tabInactive: "#757575",
    error: "#d32f2f",
    success: "#2e7d32",
    suspect: "#e65100",
    bgHover: "#f0f0f0",
    bgCode: "#f5f5f5",
    overlayBg: "rgba(0, 0, 0, 0.5)",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
  },
  sidebar: {
    width: 280,
    indent: 20,
    itemPadding: "4px 8px",
  },
  header: {
    height: 48,
  },
  fontFamily: "system-ui, -apple-system, sans-serif",
  borderRadius: 4,
} as const;
