#![allow(clippy::needless_for_each)]

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::routes;
#[derive(OpenApi)]
#[openapi(
    info(
        title = "req1 API",
        version = "1.0.0",
        description = "Requirements management API"
    ),
    modifiers(&SecurityAddon),
    paths(
        // auth (public)
        routes::auth::register,
        routes::auth::login,
        // auth (protected)
        routes::auth::me,
        routes::auth::change_password,
        // health
        routes::health::liveness,
        routes::health::readiness,
        // workspaces
        routes::workspaces::list_workspaces,
        routes::workspaces::create_workspace,
        routes::workspaces::get_workspace,
        routes::workspaces::update_workspace,
        routes::workspaces::delete_workspace,
        // projects
        routes::projects::list_projects,
        routes::projects::create_project,
        routes::projects::get_project,
        routes::projects::update_project,
        routes::projects::delete_project,
        // modules
        routes::modules::list_modules,
        routes::modules::create_module,
        routes::modules::create_module_from_template,
        routes::modules::get_module,
        routes::modules::update_module,
        routes::modules::delete_module,
        // objects
        routes::objects::list_objects,
        routes::objects::create_object,
        routes::objects::get_object,
        routes::objects::update_object,
        routes::objects::delete_object,
        routes::objects::move_object,
        routes::objects::list_object_history,
        routes::objects::search_global,
        routes::objects::sync_placeholder,
        routes::objects::break_placeholder_link,
        routes::objects::sync_all_placeholders,
        // links
        routes::links::list_links,
        routes::links::create_link,
        routes::links::get_link,
        routes::links::update_link,
        routes::links::delete_link,
        routes::links::list_link_types,
        routes::links::create_link_type,
        // baselines
        routes::baselines::list_baselines,
        routes::baselines::create_baseline,
        routes::baselines::get_baseline,
        routes::baselines::delete_baseline,
        routes::baselines::diff_baselines,
        routes::baselines::diff_baselines_global,
        routes::baselines::list_all_baselines,
        // baseline sets
        routes::baseline_sets::list_baseline_sets,
        routes::baseline_sets::create_baseline_set,
        routes::baseline_sets::get_baseline_set,
        routes::baseline_sets::update_baseline_set,
        routes::baseline_sets::delete_baseline_set,
        // attribute definitions
        routes::attribute_definitions::list_attribute_definitions,
        routes::attribute_definitions::create_attribute_definition,
        routes::attribute_definitions::get_attribute_definition,
        routes::attribute_definitions::update_attribute_definition,
        routes::attribute_definitions::delete_attribute_definition,
        routes::attribute_definitions::get_allowed_values,
        // object types
        routes::object_types::list_object_types,
        routes::object_types::create_object_type,
        routes::object_types::get_object_type,
        routes::object_types::update_object_type,
        routes::object_types::delete_object_type,
        // views
        routes::views::list_views,
        routes::views::create_view,
        routes::views::get_view,
        routes::views::update_view,
        routes::views::delete_view,
        // comments
        routes::comments::list_comments,
        routes::comments::create_comment,
        routes::comments::get_comment,
        routes::comments::update_comment,
        routes::comments::delete_comment,
        // app users
        routes::app_users::list_users,
        routes::app_users::create_user,
        routes::app_users::get_user,
        routes::app_users::update_user,
        routes::app_users::delete_user,
        // review packages
        routes::review_packages::list_review_packages,
        routes::review_packages::create_review_package,
        routes::review_packages::get_review_package,
        routes::review_packages::update_review_package,
        routes::review_packages::delete_review_package,
        routes::review_packages::transition_status,
        routes::review_packages::voting_summary,
        // review assignments
        routes::review_assignments::list_assignments,
        routes::review_assignments::create_assignment,
        routes::review_assignments::get_assignment,
        routes::review_assignments::update_assignment,
        routes::review_assignments::delete_assignment,
        // review comments
        routes::review_comments::list_review_comments,
        routes::review_comments::create_review_comment,
        routes::review_comments::get_review_comment,
        routes::review_comments::update_review_comment,
        routes::review_comments::delete_review_comment,
        // change proposals
        routes::change_proposals::list_change_proposals,
        routes::change_proposals::create_change_proposal,
        routes::change_proposals::get_change_proposal,
        routes::change_proposals::update_change_proposal,
        routes::change_proposals::delete_change_proposal,
        // scripts
        routes::scripts::list_scripts,
        routes::scripts::create_script,
        routes::scripts::get_script,
        routes::scripts::update_script,
        routes::scripts::delete_script,
        routes::scripts::test_script,
        routes::scripts::execute_script,
        routes::scripts::batch_layout,
        routes::scripts::list_executions,
        // validation
        routes::validation::validate_module,
        // traceability
        routes::traceability::get_traceability_matrix,
        routes::traceability::get_coverage,
        // impact
        routes::impact::get_impact,
        // attachments
        routes::attachments::list_attachments,
        routes::attachments::upload_attachment,
        routes::attachments::download_attachment,
        routes::attachments::verify_attachment,
        routes::attachments::delete_attachment,
        // webhooks
        routes::webhooks::list_webhooks,
        routes::webhooks::create_webhook,
        routes::webhooks::get_webhook,
        routes::webhooks::update_webhook,
        routes::webhooks::delete_webhook,
        // lifecycle
        routes::lifecycle::list_lifecycle_models,
        routes::lifecycle::create_lifecycle_model,
        routes::lifecycle::get_lifecycle_model,
        routes::lifecycle::update_lifecycle_model,
        routes::lifecycle::delete_lifecycle_model,
        // publish/import
        routes::publish::publish_module,
        routes::publish::import_csv,
        routes::publish::import_xlsx,
        routes::publish::preview_docx,
        routes::publish::import_docx,
        // reqif
        routes::reqif::import_reqif_handler,
        routes::reqif::export_reqif_handler,
        // tests
        routes::tests::list_test_cases,
        routes::tests::create_test_case,
        routes::tests::get_test_case,
        routes::tests::update_test_case,
        routes::tests::delete_test_case,
        routes::tests::list_test_executions,
        routes::tests::create_test_execution,
        routes::tests::get_test_execution,
        routes::tests::update_test_execution,
        routes::tests::delete_test_execution,
        routes::tests::get_test_coverage,
        routes::tests::get_test_dashboard,
        // audit
        routes::audit::list_audit_logs,
        // diagrams
        routes::diagrams::list_diagrams,
        routes::diagrams::create_diagram,
        routes::diagrams::get_diagram,
        routes::diagrams::update_diagram,
        routes::diagrams::delete_diagram,
        // notifications
        routes::notifications::list_notifications,
        routes::notifications::unread_count,
        routes::notifications::mark_read,
        routes::notifications::mark_all_read,
        // e-signatures
        routes::e_signatures::create_signature,
        routes::e_signatures::list_signatures,
        // dashboards
        routes::dashboards::list_dashboards,
        routes::dashboards::create_dashboard,
        routes::dashboards::get_dashboard,
        routes::dashboards::update_dashboard,
        routes::dashboards::delete_dashboard,
        routes::dashboards::list_widgets,
        routes::dashboards::create_widget,
        routes::dashboards::get_widget,
        routes::dashboards::update_widget,
        routes::dashboards::delete_widget,
        routes::dashboards::get_widget_data,
        routes::dashboards::export_pdf,
        // project templates
        routes::project_templates::list_templates,
        routes::project_templates::create_template,
        routes::project_templates::get_template,
        routes::project_templates::update_template,
        routes::project_templates::delete_template,
        routes::project_templates::instantiate_template,
    ),
    components(schemas(
        // Entity models
        entity::app_user::Model,
        entity::attachment::Model,
        entity::attribute_definition::Model,
        entity::audit_log::Model,
        entity::baseline::Model,
        entity::baseline_entry::Model,
        entity::baseline_set::Model,
        entity::change_proposal::Model,
        entity::comment::Model,
        entity::dashboard::Model,
        entity::dashboard_widget::Model,
        entity::diagram::Model,
        entity::e_signature::Model,
        entity::lifecycle_model::Model,
        entity::link::Model,
        entity::link_type::Model,
        entity::module::Model,
        entity::module_permission::Model,
        entity::notification::Model,
        entity::object::Model,
        entity::object_history::Model,
        entity::object_type::Model,
        entity::project::Model,
        entity::project_template::Model,
        entity::review_assignment::Model,
        entity::review_comment::Model,
        entity::review_package::Model,
        entity::script::Model,
        entity::script_execution::Model,
        entity::test_case::Model,
        entity::test_execution::Model,
        entity::view::Model,
        entity::webhook::Model,
        entity::workspace::Model,
        entity::workspace_member::Model,
        // Core types
        req1_core::PaginatedResponse<serde_json::Value>,
        req1_core::auth::AuthUser,
        // Service DTOs
        req1_core::service::auth::LoginResponse,
        req1_core::service::project::CreateProjectInput,
        req1_core::service::project::UpdateProjectInput,
        req1_core::service::workspace::CreateWorkspaceInput,
        req1_core::service::workspace::UpdateWorkspaceInput,
        req1_core::service::module::CreateModuleInput,
        req1_core::service::module::UpdateModuleInput,
        req1_core::service::module::CreateModuleFromTemplateInput,
        req1_core::service::object::CreateObjectInput,
        req1_core::service::object::UpdateObjectInput,
        req1_core::service::object::MoveObjectInput,
        req1_core::service::object::GlobalSearchResult,
        req1_core::service::link::CreateLinkInput,
        req1_core::service::link::UpdateLinkInput,
        req1_core::service::link::CreateLinkTypeInput,
        req1_core::service::baseline::CreateBaselineInput,
        req1_core::service::baseline::BaselineWithEntries,
        req1_core::service::baseline::BaselineDiff,
        req1_core::service::baseline::DiffEntry,
        req1_core::service::baseline::DiffModified,
        req1_core::service::baseline_set::CreateBaselineSetInput,
        req1_core::service::baseline_set::UpdateBaselineSetInput,
        req1_core::service::comment::CreateCommentInput,
        req1_core::service::comment::UpdateCommentInput,
        req1_core::service::app_user::CreateAppUserInput,
        req1_core::service::app_user::UpdateAppUserInput,
        req1_core::service::change_proposal::CreateChangeProposalInput,
        req1_core::service::change_proposal::UpdateChangeProposalInput,
        req1_core::service::review_package::CreateReviewPackageInput,
        req1_core::service::review_package::UpdateReviewPackageInput,
        req1_core::service::review_package::VotingSummary,
        req1_core::service::review_assignment::CreateReviewAssignmentInput,
        req1_core::service::review_assignment::UpdateReviewAssignmentInput,
        req1_core::service::review_comment::CreateReviewCommentInput,
        req1_core::service::review_comment::UpdateReviewCommentInput,
        req1_core::service::object_type::CreateObjectTypeInput,
        req1_core::service::object_type::UpdateObjectTypeInput,
        req1_core::service::view::CreateViewInput,
        req1_core::service::view::UpdateViewInput,
        req1_core::service::webhook::CreateWebhookInput,
        req1_core::service::webhook::UpdateWebhookInput,
        req1_core::service::lifecycle::CreateLifecycleModelInput,
        req1_core::service::lifecycle::UpdateLifecycleModelInput,
        req1_core::service::lifecycle::LifecycleState,
        req1_core::service::lifecycle::LifecycleTransition,
        req1_core::service::diagram::CreateDiagramInput,
        req1_core::service::diagram::UpdateDiagramInput,
        req1_core::service::dashboard::CreateDashboardInput,
        req1_core::service::dashboard::UpdateDashboardInput,
        req1_core::service::dashboard::CreateWidgetInput,
        req1_core::service::dashboard::UpdateWidgetInput,
        req1_core::service::dashboard::WidgetDataEntry,
        req1_core::service::e_signature::SignInput,
        req1_core::service::project_template::CreateTemplateInput,
        req1_core::service::project_template::UpdateTemplateInput,
        req1_core::service::project_template::InstantiateInput,
        req1_core::service::project_template::InstantiateResult,
        req1_core::service::test::CreateTestCaseInput,
        req1_core::service::test::UpdateTestCaseInput,
        req1_core::service::test::CreateTestExecutionInput,
        req1_core::service::test::UpdateTestExecutionInput,
        req1_core::service::test::TestCoverageResponse,
        req1_core::service::test::TestStatusCounts,
        req1_core::service::test::TestDashboardSummary,
        req1_core::service::test::TestCaseStatusCounts,
        req1_core::service::test::TestPriorityCounts,
        req1_core::service::validation_service::ValidationReport,
        req1_core::service::validation_service::ValidationIssue,
        req1_core::service::csv_import::CsvImportResult,
        req1_core::service::xlsx_import::XlsxImportResult,
        req1_core::service::docx_import::DocxPreviewResult,
        req1_core::service::docx_import::DocxImportResult,
        req1_core::service::docx_import::DiscoveredStyle,
        req1_core::service::docx_import::StyleMapping,
        req1_core::service::docx_import::DocxImportInput,
        // Route-local types
        routes::health::HealthResponse,
        routes::objects::SearchQuery,
        routes::objects::SearchResponse,
        routes::objects::SyncAllResponse,
        routes::baselines::CreateBaselineRequest,
        routes::attachments::VerifyResult,
        routes::impact::ImpactObject,
        routes::impact::ImpactEdge,
        routes::impact::ImpactResponse,
        routes::traceability::MatrixObject,
        routes::traceability::MatrixCell,
        routes::traceability::TraceabilityMatrixResponse,
        routes::traceability::CoverageResponse,
        routes::notifications::UnreadCountResponse,
        routes::notifications::MarkAllReadResponse,
        routes::scripts::CreateScriptRequest,
        routes::scripts::UpdateScriptRequest,
        routes::scripts::TestScriptRequest,
        routes::scripts::ExecuteResult,
        routes::scripts::BatchLayoutResponse,
        routes::scripts::LayoutEntry,
        routes::publish::CsvImportResponse,
        routes::publish::XlsxImportResponse,
        routes::reqif::ImportResponse,
        routes::e_signatures::CreateSignatureRequest,
        routes::webhooks::CreateWebhookRequest,
        routes::webhooks::UpdateWebhookRequest,
        routes::review_packages::TransitionRequest,
        routes::attribute_definitions::CreateAttributeDefinitionRequest,
        routes::attribute_definitions::UpdateAttributeDefinitionRequest,
        routes::auth::RegisterRequest,
        routes::auth::LoginRequest,
        routes::auth::ChangePasswordRequest,
    ))
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}
